# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[main]]
identifier = "itch"
name = "Itch.io"
url = "https://okutasan.itch.io/"
weight = 3

[main.params]
icon = "gamepad"
newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/okutasan"

[social.params]
icon = "brand-github"

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/okutasan"  

[social.params]
icon = "brand-linkedin"
